### ISSUE TITLE
Plugin for logstash>2.0.0

### ISSUE THREAD

**Issue by kurkop** [phutchins/logstash-input-mongodb#33]
Hi,

I want used logstash with the plugin, but I understand that is not avalaible for logstash>2.0.0. Are you planning to upgrade?

https://github.com/elastic/logstash/issues/4169

```
plugin install logstash-input-mongodb
 ---> Running in 062b87f7ae18
Validating logstash-input-mongodb
Installing logstash-input-mongodb
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash":
  In Gemfile:
    logstash-input-mongodb (>= 0) java depends on
      logstash (< 2.0.0, >= 1.4.0) java
Could not find gem 'logstash (< 2.0.0, >= 1.4.0) java', which is required by gem 'logstash-input-mongodb (>= 0) java', in any of the sources.
The command '/bin/sh -c ${LOGSTASH_SRC_DIR}/bin/plugin install logstash-input-mongodb' returned a non-zero code: 1
```

**Comment by Surt** [comment]
+1

**Comment by phutchins** [comment]
Thanks for reporting this. I'm taking a look at it now.

**Comment by phutchins** [comment]
Turns out I'd simply not pushed the newer versions of the plugin to rubygems.org. I've pushed and was able to install. Make sure to check the docs to ensure that your config is compatible with the new versions. I've made a few changes, most of which should be backwards/forwards compatible, but always good to confirm...

` logstash-plugin install logstash-input-mongodb
Validating logstash-input-mongodb
Installing logstash-input-mongodb
Installation successful
`

Please let me know if you see any issues in the transition from 1.x or 2.x to 3.3.
